version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:v7.0.0-beta.0
    ports:
      - "8545:8545"
    networks:
      - ganache
    command: ganache-cli -h 0.0.0.0 -p 8545 -i 1337 -s foobar -e 100000000000000000000

  truffle:
    build:
      context: .
      dockerfile: Dockerfile.truffle
    networks:
      - ganache

networks:
  ganache:
